dist: xenial   # required for Python >= 3.7
language: python

python:
  - "3.6"
  - "3.7"
  - "nightly"

### command to install dependencies
install: "pip install -r requirements.txt"

### command to run linters and tests
script:
- |
  make check
  codecov
